from .ai_framework import FrameWorkDetails
from .ai_model import *
from .ai_model_infer_job import AIInferJobs
from .deployed_job_data import DeployedJobsData
from .deployed_job_rtsp_data import DeployedRTSPJobsData
from .deployment_job import DeploymentJob
from .deployment_job_rtsp import *
from .deployment_type import DeploymentType
from .device import Device
from .label_setting import LabelSetting
from .model_type import ModelType
from .result_feedback import ResultFeedback
from .result_feedback_image import ResultFeedbackImage
from .user import User, UserRoles, Company
from .location import *
from .model_test_credit import ModelTestCredit
from .feedback import Feedback
from .complaint import Complaint
from .notification import Notification
from .employee import Employee
from .company_setting import CompanySetting
from .violation_setting import ViolationSetting
from .model_main_category import ModelMainCategory
from .demog_emp import DemogEmp
from .demog_department import DepartmentDetails
from .demog_location import LocationDetails
from .rtsp_down_odit import RtspDownOdit
from .scheduler_time import SchedulerTime
from .vehicle_details import VehicleDetails
from .anpr_vms_details import AnprVmsDetails
from .notification_config import NotificationConfig
